### ISSUE TITLE
Enhancement: extension point for protected asset HTTPResponse

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-assets#107]
Currently it’s only possible to add generic headers to _all_ files via `file_response_headers`. The ability to update the `HTTPResponse` seems like a reasonable addition to me, e.g. to add headers based on file extension.

Such an extension hook could be added to either:
- `createResponseFor()` and `createErrorResponse()` in `FlysystemAssetStore`
- my preference - `ProtectedFileController::handleFile()`

Will submit a PR if this gets a thumbs up

**Comment by chillu** [comment]
What's the use case for adding other headers here? If you add it to `ProtectedFileController`, presumably it's further restrictions on how the response can be cached or handled by clients? We couldn't use it for cache lifetime on public assets, since those aren't going through this layer.

I'd opt for `createResponseFor()` because you'll likely want the MIME type rather than the file extension to determine conditional behaviour. And that requires reading the file, an expensive operation which shouldn't be done twice, right?

Either way it's implemented, I'd only be in favour if it doesn't affect performance of this critical path.

**Comment by kinglozzer** [comment]
> What's the use case for adding other headers here?

I should really have added that to the issue, because I don’t recall now... I _think_ what prompted me to create this was something I saw on Slack about issues streaming video from `assets/.protected`, and adding some headers was one proposed solution (I don’t remember if it was _the_ solution).

**Comment by kinglozzer** [comment]
A year later I still haven’t bothered, obviously not high priority
