### ISSUE TITLE
Files with dots in filename will no longer be served.

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-assets#141]
Introduced with version `1.1.1`, specifically: https://github.com/silverstripe/silverstripe-assets/commit/1e27835e0e7619de734c8b79074e4c7d8cfc071b

The addition of `^[^.]*` to the rewrite condition will deny access to files that have a dot in the filename. Example:
`assets/myfolder/d0ee4b8243/test.2.png` -> 403
whereas `assets/myfolder/d0ee4b8243/test.png` works as expected

Since dots are still allowed characters in a filename (eg. they don't get replaced when a file is being uploaded), this is probably a bug.

**Comment by andrewandante** [comment]
This also appears to break a fresh install of 4.1.1: see https://forum.silverstripe.org/t/unable-to-edit-pages-on-a-fresh-install-local-environment/538/11

Think this change either needs to be reverted or reconsidered

**Comment by chillu** [comment]
Sigh ... Prioritising as `impact/high`

**Comment by tractorcow** [comment]
We can fix by changing the pattern, instead of 'non-dot characters plus one dot' rule, it should be 'any number of dots, as long as all dots are after all slashes'. That will fix this issue without re-introducing the security vulnerability (i.e. risky 'file.php/nothing.jpg' being mis-interpreted as a jpg, but then executing).

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-assets/pull/158.

I've checked this doesn't re-open https://www.silverstripe.org/download/security-releases/ss-2018-012 but it's worth a double check.

**Comment by tractorcow** [comment]
Also, folders in dots will never be allowed, since that is the specific security issue.

**Comment by michalkleiner** [comment]
Is there a better way to check if the path (folder name with dots) is insecure? E.g. split into chunks and check for files instead of folders? Shouldn't be that hard. Limiting standard filesystem usage where people should be able to name things as they normally do seems too restrictive without further guidance.

**Comment by bummzack** [comment]
I think the problem is that it has to be done in `.htaccess`, otherwise you'd have to serve each and every file through the framework. I think disallowing dots in folder-names is acceptable (these are created via CMS anyway and can be renamed accordingly)

**Comment by bummzack** [comment]
@michalkleiner yeah, but that only applies to draft content. Only these files are served through the Framework, the ones in the public asset folder are served directly (eg. much faster)

**Comment by tractorcow** [comment]
If you really really wanted dots in folders, we could force it to follow allowed_extensions rules.

On the other hand, that's kind of weird because they aren't files. :P It also isn't obvious at routing time what is and isn't a folder, since you can route to files even if they have `/otherpath` on the end.

Simplest is to disallow all extensions on folders and force it at both the code and the routing (htaccess) level.
