### ISSUE TITLE
Image Resampling configuration

### ISSUE THREAD

**Issue by ColmMcBarron** [silverstripe/silverstripe-assets#21]
In the docs: 
https://docs.silverstripe.org/en/4/developer_guides/files/images/ 

It says that the images will not be resampled by default, however the code does resample by default (private static $force_resample = true;) in the ImageManipulation trait.

So if you upload an already compressed image, it looks quite bad, so I changed the option in the YAML file to correct this issue for now.

**Comment by dhensby** [comment]
@tractorcow do you know if this is intended? should we turn off force_resample or amend the docs?

**Comment by tractorcow** [comment]
Oh, the docs are out of date. resample by default is on intentionally.

**Comment by dhensby** [comment]
ok, thanks. I'll update the docs.

**Comment by dhensby** [comment]
Can you provide me some context as to why it's on so the docs can explain that and possibly highlight why people may not wish to change this setting?

**Comment by tractorcow** [comment]
The new preference by default is performance over quality. Large images will stop slowing down pages if left un-sampled. I believe @jonom was the driver behind this.

**Comment by jonom** [comment]
Yeah here is the commit: https://github.com/silverstripe/silverstripe-framework/commit/40cc567c368cc8bc633c2486ca2c420bb1256924

Basic idea is that since SilverStripe handles all your image manipulations and compresses them for output, you should be aiming to upload hiqh quality (minimal or no compression) source images to your assets store, so you're not compressing images twice over and getting a messy result.

If you do follow that practice, you don't want to send out the source images to the client as they will be much larger than they need to be. SilverStripe previously skipped resampling and sent out the original image if it already matched the target resize dimensions, so @stevie-mayhew introduced the `$force_resample` property to prevent this scenario.

I thought it made sense to turn it on be default for SS4, to make image output more consistent and protect users from large downloads. Appears I dropped the ball on updating the docs though, sorry!

@dhensby let me know if you'd like me to update the docs since I should have done it in the first place ;)

**Comment by dhensby** [comment]
@jonom yes please if you have the time!

**Comment by youpixxl** [comment]
Hello,
Sorry I know this one is closed by I am still seeing inconsistency between doc and vendor files.
I just run a new composer installation ^4 to check and in there force_resample is still set to false (ImageManipulation.php line 179).

Also the Images documentation page ([https://docs.silverstripe.org/en/4/developer_guides/files/images/]) still mention that force_resample is off by default, and the code given to turn it on did not work for me. 

I was finally able to turn it on by changing config on DBFile.php in my config.yml

`SilverStripe\Assets\Storage\DBFile:
force_resample: true`

I may have missed something here and if this is the case sorry to reopen this, but as I struggled for sometimes to find this I thought it was worth mentioning it and maybe it could help others.

**Comment by tractorcow** [comment]
We'll update the docs, thanks for pointing out the inconsistency.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/7908
