### ISSUE TITLE
File::canView() not checked when a File is linked from a Page

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-assets#220]
Splitting out of https://github.com/silverstripe/silverstripe-framework/issues/8493 which is bigger and more amorphous.

If you have Page that embeds a File, the File's canView() permission is _not_ checked before granting access to the File. This breaks the security model, although requires that an author links to a protected file from a non-protected page in the CMS, so I would rate it as low severity (which is why I've posted it to the public issue list).

The relevant code is here: https://github.com/silverstripe/silverstripe-assets/blob/1/src/Shortcodes/FileShortcodeProvider.php#L72

This check should be checking File::canView(). If we do this, that should address Ingo's concern that custom canView() implementations wouldn't be respected.

**Edit:** This issue has been reopened. See [comment](https://github.com/silverstripe/silverstripe-assets/issues/220#issuecomment-571856130) below

## PRs
 - [x] https://github.com/silverstripe/silverstripe-assets/pull/402
- [x] https://github.com/silverstripe/silverstripe-assets/pull/403

**Comment by sminnee** [comment]
FYI @chillu @maxime-rainville

**Comment by maxime-rainville** [comment]
Just making sure we're looking at the same thing. I reproduce with this step.

1. Upload an image and define its "Who can view" permission to logged in user.
1. Publish the file.
1. You should be able to view in the file in your current browser session. However, if you open the file url in a different browser, you'll get a file not found.
1. Add the image to a page WYSIWYG and publish.
1. Access the page in the anonymous browser session.

Expected behaviour: You see a broken link on the page.
Actual behaviour: You see the file.

**Comment by sminnee** [comment]
Yeah that sounds about right. step 3 is kind of an optional step and suffers from #221 which is much less important to fix, so don't get distracted by that!

**Comment by chillu** [comment]
>  If we do this, that should address Ingo's concern that custom canView() implementations wouldn't be respected.

Only if those behave predictably for anonymous users (e.g. no embargo/expiry or other time based logic). But we've already agreed to document that gotcha as part of #221 so I'm good with that.

> This check should be checking File::canView().

So the expected behaviour is "you see a broken link on the page". That's fixing the immediate issue (access granted where it shouldn't). But it's not a great authoring experience. I've filed yet another new issue for that: https://github.com/silverstripe/silverstripe-asset-admin/issues/921

**Comment by UndefinedOffset** [comment]
I just ran into this issue with one of the clients I work with, nice bug. We're may try and come up with a workaround for this issue that would at least fix it on the client's site. But I have a funny feeling it would only work in conjunction with our webbuilders-group/silverstripe-login-files module since it checks `File::canView()` then grants access to said file if you do.

**Comment by UndefinedOffset** [comment]
I wonder should this also be tagged as security? Arguably this could be considered a security issue.

**Comment by kinglozzer** [comment]
Ah, we’ve already fixed this as part of [CVE-2019-14273](https://github.com/silverstripe/silverstripe-assets/commit/8c7a71992b038f65543a37097b88e6929c23ba8b), so this should behave as expected in assets 1.4.5. Looks like we just forgot to close this issue off :)

**Comment by brynwhyman** [comment]
Sorry to revive an old issue, but I'm still experiencing a part of this problem with `silverstripe/assets 1.5.0` installed.

Steps to reproduce are the same as https://github.com/silverstripe/silverstripe-assets/issues/220#issuecomment-472259680:

> Upload an image and define its "Who can view" permission to logged in user.
Publish the file.
Add the image to a page WYSIWYG and publish.
Access the page in the anonymous browser session.
Expected behaviour: You see a broken link on the page.
Actual behaviour: You see the file.

I've had a look at the [private security issue](https://github.com/silverstripe-security/security-issues/issues/60) comments and it looks like the the committed fix ensures that links to a protected file on a published page will correctly 404, but it seems to have missed the use case where a protected/private file (like an image) is embedded on the page.

Admittedly, this is pretty low impact but raising here first...

**Comment by dnsl48** [comment]
The access to embedded files has been fixed in the security issue, but images have their own handler. A PR with a follow-up fix is here https://github.com/silverstripe/silverstripe-assets/pull/402

**Comment by dnsl48** [comment]
Fixed in 4.6.0

**Comment by Cheddam** [comment]
I hate to be the bearer of bad news, but unfortunately an edgecase still exists in both cases - the first user to load a page containing a restricted file after a cache flush is still granted access to that file, because the uncached logic branch still calls `$record->Link()` to get the URL for the asset.

`File::Link()` is a _giant_ footgun that implicitly produces session grants, with no option to disable this behaviour. We should look at API adjustments to address this, but I'll save that for another issue.

Here's a further PR to address the edgecase outlined above: #403
