### ISSUE TITLE
ShowInSearch should default to 0

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-assets#247]
This is the SS4 version of this SS3 issue https://github.com/silverstripe/silverstripe-secureassets/issues/69

Apologies if the following is incorrect for SS4, the issue below was originally written for an issue that affected the SS3 secureassets module

File.ShowInSearch should be set to 0 for files that go into a secure assets folder

There should be a yml config option to change this to 1 if desired, because this may be desired if the person performing the search has relevant canView() permissions

Probably the most standard use case for secureassets is a public user uploads files from a UserDefinedForms. By default, UserDefinedForms will set ShowInSearch = 0

However, if there is a custom form, or another method of adding files to a secureassets folder, then ShowInSearch retains its default value of 1 which is set in File.php - this leads to the not so good scenario where secure assets may show in search if a custom search engine does not have a canView() check

**Comment by maxime-rainville** [comment]
Just had a look.

It doesn't look like `ShowInSearch` is unset when access to a File is restricted. Don't think it will actually matter, because [SearchForm](https://github.com/silverstripe/silverstripe-fulltextsearch/blob/afc6364d22d2d2f7d811d791b0bfdb24c677930f/src/Solr/Forms/SearchForm.php#L89) does a `CanView` check to filter out results you don't have access to. This sounds like a pretty sensible behaviour.

The [doc for fulltextsearch](https://github.com/silverstripe/silverstripe-fulltextsearch/blob/3/docs/en/03_configuration.md#adding-dataobjects) states:
> getShowInSearch() is required to get the record to show in search, since all results are filtered by ShowInSearch.

However, a search through the fulltextsearch codebase doesn't return any relevant reference to `ShowInSearch`, so my guess right now is that it's ignored ... which sounds problematic.

I'm setting the impact of this to high because, if it's actually broken, it could lead to leaking data through search.

**Comment by maxime-rainville** [comment]
The CMS `SearchForm` also filters out results by CanView. It also doesn't reference the `ShowInSearch` field.

**Comment by chillu** [comment]
What Max said. The real check is `canView()`, which returns `false` for anonymous users on protected files. 

I've created related issues around [don't index records with ShowInSearch=false](https://github.com/silverstripe/silverstripe-fulltextsearch/issues/257) and [don't index records where canView=false for anonymous users](https://github.com/silverstripe/silverstripe-fulltextsearch/issues/252). Let's continue discussion over there.
