### ISSUE TITLE
FileMigrationHelper: Issue with case sensitive folder paths

### ISSUE THREAD

**Issue by ichaber** [silverstripe/silverstripe-assets#273]
## Affected Version

This issue was found on SilverStripe 4.4-rc1 (4a0f62fafd13bfc90a1498a632a6fec9ea27d039). 

## Description

Files in a folder with an uppercase name and an entry in the database with a lowercase folder will not be migrated when running the `MigrateFileTask`. That is, because the look up in a case-sensitive file system (e.g. `ext4`) will not find the file in a lower case folder. 

Furthermore this leads to a collision, if two folder have the same name with only the difference being the case and two different entries in the database. 

## Steps to Reproduce

1. Place an image in a folder with an uppercase name (e.g. assets/**P**lanning/diagram.jpg)
2. Create a corresponding entry in the `File` table with a `Filename` having the folder in a lowercase format (e.g. assets/**p**lanning/diagram.jpg)
3. Running the `/dev/tasks/MigrateFileTask` task.
3. Observe, that the file will not be found and hence not migrated.

## Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/277

**Comment by maxime-rainville** [comment]
So I did a quick PR that adds some test case around file names with conflictual/contradicatory filenames. https://github.com/silverstripe/silverstripe-assets/pull/277 

Here's what I'm testing and the end results.

DB | Filesystem | End results
-- | ---------- | -----------
wrong-case.txt | wRoNg-CaSe.tXt | Fails to import
uploads/good-case-bad-folder.txt | uploads/good-case-bad-folder.txt | Fails to import
Uploas/good-case-good-folder.txt | Uploas/good-case-good-folder.txt | Success
MIXED-CASE-FILE.TXT | MIXED-CASE-FILE.TXT | This is the first file, it imports successfully
mixed-case-file.txt | mixed-case-file.txt | Seems to import correctly, but it probably should be renamed mixed-case-file-v2.txt to avoid conflicts with the previous file.

This was on a linux box. The first 2 cases might have worked on a Windows system because they are case insensitive. Not sure about `mixed-case-file.txt` and if that scenario is even possible on Windows.

**Comment by maxime-rainville** [comment]
I had a quick look to see if there's a way to do a case insensitive file existence check on Flysystem ... it doesn't look like there is.

The only way I could do this is to load the entire file system store tree and lowercase it and do my own comparison to the expected file name from the DB.

**Comment by chillu** [comment]
I'm still struggling to see how a site could get into this state through CMS author actions, or custom PHP code. @ichaber is there any pattern to those inconsistent files, e.g. user uploads? Are there actually duplicates in different casings in the same folder? How many files were affected by this?

Looking at [Filesystem->sync()](https://github.com/silverstripe/silverstripe-framework/blob/3/filesystem/Filesystem.php#L183) and [Folder->syncChildren()](https://github.com/silverstripe/silverstripe-framework/blob/3/filesystem/Folder.php#L91), I can't see how that messes with the filename: When looping through the filesystem, it uses `constructChild()` to write a new database entry, without altering the filename casing.

The examples are a bit confusing:
 * `uploads/good-case-bad-folder.txt` is the same on DB and filesystem (no case mixups) - I'd assume that imports? 
 * `MIXED-CASE-FILE.TXT` and `mixed-case-file.txt` don't contain mixed case. I'm also not sure what "This is the first file, it imports successfully" means

> The only way I could do this is to load the entire file system store tree and lowercase it and do my own comparison to the expected file name from the DB.

Or the other way around: Loop through each file and folder on the filesystem, and adjust the database entry accordingly if it's different - since in the database, we can run case insensitive searches, in the filesystem we can't (easily).

Actually, how about we *only* run the logic when a database entry can't be found on the filesystem, on that particular folder? That should limit the performance impact a bit, right? With the assumption that the minority of files exhibit this problem.

**Comment by maxime-rainville** [comment]
That approach could work ... however we have to be mindful that it's possible to have 2 files with the same name different casing. In which case, I'm not sure what we'll do if we can't find the second file.

> uploads/good-case-bad-folder.txt is the same on DB and filesystem (no case mixups) - I'd assume that imports?
Sorry ... the `upload` folder was mix-match in this case.

> MIXED-CASE-FILE.TXT and mixed-case-file.txt don't contain mixed case. I'm also not sure what "This is the first file, it imports successfully" **means**

This is more a covering our basis test case. Once we have logic to rename files base on their case insensitive filename, this should still work ... and maybe add a `-v2` suffix to the filename.

It would also be interesting to have this specific test run on Windows to see how it handles that specific use case.

**Comment by maxime-rainville** [comment]
On how you could end up with a mis-match case, I have this weird theory.

You upload a file on a Windows hosted SilverStripe site. You rename the file to use different cases. The DB entry gets updated, however the physical move operation doesn't do anything because the file system is case insensitive. In the short term, this doesn't change anything because the file will still be served up as expected.

I had a similar issue where I was collaborating with a bunch of people on Windows and they kept moving files around and GIT was tracking those as duplicates and the entire thing was driving up the wall.

**Comment by maxime-rainville** [comment]
Fixed by #277
