### ISSUE TITLE
RewriteEngine in assets

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-assets#353]
In silverstripe-assets [`RewriteEngine On`](https://github.com/silverstripe/silverstripe-assets/blob/1/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss#L21) is set and since it's a subfolder of public, it "resets" the rewrite rules from there - they won't be inherited to `public/assets`. If you for example force httpS in `public/.htaccess` with a snipped like below, it won't be respected in `public/assets` (even tough your browser may redirect, it won't server-side - try safari).
```
RewriteCond %{SERVER_PORT} !^443 [NC]
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [r=301,L]
```
Forcing httpS per htaccess is common practice and depending on hosting, it's the most practicable way achieving it universally over a site. It would be beneficial if assets doesn't "break" that use case. Otherwise it's getting unnecessary complex if you have to maintain htaccess-templates just for this. Also the behavior is rather unexpected. Would it be possible to just inherit it from public?

**Comment by chillu** [comment]
Looking at the [RewriteEngine docs](https://httpd.apache.org/docs/current/mod/mod_rewrite.html#RewriteEngine), there is no indication that using this directive repeatedly with the same value (`On`) causes a reset. But I wouldn't be surprised if it does. Which version of Apache are you using?

I think we might be able to get away without `RewriteEngine On` in `public/assets/.htaccess`, since you can't really operate Silverstripe on Apache without it already being enabled on `public/.htaccess`. The same should be true for usage without public webroot. Can you confirm that removing this line fixes your issue, still routes protected files properly, and still blocks invalid file extensions?

**Comment by lerni** [comment]
Well I thought disabling did the trick but now I can't replicate on a different environment :( I 'll try to investigate some more.

**Comment by lerni** [comment]
I've tested with homebrew httpd 2.4.41 & and with litespeed on cloudelinux - the presence of any in `assets/.htaccess` redirection made the redirection from public fail. By default child htaccess-files do not inherit parent rules. `RewriteOptions Inherit` or `RewriteOptions InheritBefore` made it behave that way. Later is just available from apache 2.3.10 onwards - `Inherit` is supported way back to 1.3.

http://httpd.apache.org/docs/1.3/mod/mod_rewrite.html#rewriteoptions
http://httpd.apache.org/docs/2.4/mod/mod_rewrite.html#rewriteoptions

Adding `RewriteOptions Inherit` right after [`RewriteEngine On`](https://github.com/silverstripe/silverstripe-assets/blob/1/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss#L21) (order shouldn't matter) made the redirection also work within assets. As far as I can see protected continues to work as expected but I'm unsure about file extension - either way I could up- & download whatever file extension.

**Comment by lerni** [comment]
I was wrong about file-extensions - it works as expected also with `RewriteOptions Inherit` (image engine added correct extension like file.jpeeeeg.jpeg and browser hidded URL)

**Comment by chillu** [comment]
Right, thanks for investigating! So what I'm hearing here is that if you want to use custom `RewriteRule` in a certain way, then you need to understand it and customise it properly (with the `Inherit` option). I have to admit that I wouldn't have expected this either though. Maybe we can add a comment to the base file at https://github.com/silverstripe/recipe-core/blob/4/public/.htaccess? Something like "If you expect rewrites to apply to assets/, please use inherit". 

Alternatively, we could try and move the assets rewrite into the base htaccess, but then we need to generate that base htaccess dynamically due to "allowed extensions" (see [template](https://github.com/silverstripe/silverstripe-assets/blob/1/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss)). That sounds like a pain, and makes for error prone upgrades? I don't think we can get rid of this security mechanism (even though it's only "defense in depth" on top of the upload restrictions).

**Comment by lerni** [comment]
The aim of this request was to prevent the necessity to customize assets-htaccess-templates [two-times](https://github.com/silverstripe/silverstripe-assets/tree/1/templates/SilverStripe/Assets/Flysystem), just to enforce https in /assets on hostings, where you don't have access to vhost-config. Setting it per opt-in yml-config in silverstripe-assets would be an relative easy option to?

**Comment by chillu** [comment]
> Setting it per opt-in yml-config in silverstripe-assets would be an relative easy option to?

I'm already uncomfortable with our level of reliance on htaccess, and the fact that we generate those dynamically. Not super keen to add more complexity to this. I'd recommend that you write a forum post outlining how you've fixed the issue, in a way that makes it easy for others to find. Maybe add a comment to the `assets/.htaccess` template which makes it clear that rewrite rules aren't inherited?

**Comment by lerni** [comment]
Well I can understand that and it made me discover, that from 2.4.8 onwards `InheritDown` is available, so you can set it in `public/.htaccess` and don't have to edit all subsequent `.htaccess` files. Thank you Ingo for your feedback, I'll add a comment as you suggested.

**Comment by chillu** [comment]
Sweet, I'm closing this issue since I don't think there's any immediate action in the framework required, but as discussed, happy to review a pull request for that comment. Please ping me in that, otherwise I might miss it.
