### ISSUE TITLE
Editing image will make hash invalid

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-assets#378]
So here is my scenario

I have a customer uploading some really large images which makes GD very unhappy. Although this is a problem in itself (and I'd love to see the day where silverstripe will properly handle pixel size constraints based on available memory for gd, or do client side resizing), I decided to fix this by downloading the assets, resizing the images manually, and upload them again.

But now the issue is : the hash are invalid!  And images are displayed as not found even if the file exists

There should be a way to recompute hash when file exists in case files are modified by an external utility

**Comment by kinglozzer** [comment]
Firstly, I’d recommend looking into switching to Imagick if that’s possible in your hosting environment. Content authors can upload all the 100mb JPGs they like then :wink:.

Have you tried using the “replace file” option in the CMS? (when editing a file, it’s under the `•••` button)

**Comment by lekoala** [comment]
@kinglozzer imagick is possible, but it's still a bit sad that the default setup has this issue. i can replace files, but that means do this manually for every file.

in the meantime i came up with this
https://github.com/lekoala/silverstripe-base/blob/master/src/Dev/Tasks/RehashImagesTask.php

if it can help someone :-)

**Comment by emteknetnz** [comment]
@lekoala 

Just to let you know we're closing this feature request as the bug tracker is not the best place to discuss potential enhancements.  You can read more about the guide on [contributing issues](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#feature-requests) and you are welcome to raise new feature ideas on the [Silverstripe forum](https://forum.silverstripe.org/c/feature-ideas) instead.

**Comment by 3Dgoo** [comment]
I just came across this issue. I think having a dev task to fix any broken image hashes is a good idea. It would be good to have this build task as apart of this assets module.

If we were to do a pull request adding this feature in, would that be something that is welcome?

**Comment by patricknelson** [comment]
I’m curious as to why this architectural approach was taken in the first place. I happen to also be catching up with how SS v4 is doing things and I noticed the presence of a hash (same hash?) in the URL prefixing filenames as I read through the change longs (e.g. https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.4.0.md). Is there a discussion/RFC explaining the rationale for this? I’ve already implemented something myself years ago for CDN cache busting by just keeping track of the upload version and appending that to the URL (e.g. `file.jpg?v=2`) which works even if the file is deleted since it’s maintained in a separate table by URL and only is affected in CMS/DB changes (so changing the file doesn’t break everything, as versioning is entirely DB driven).

I’m sure there’s a good reason for this, but wanted to study up a bit more.

**Comment by patricknelson** [comment]
Never mind my question, I found the RFC regarding this in the `silverstripe-framework` repo: https://github.com/silverstripe/silverstripe-framework/issues/3792

And documentation on how that all works here: https://docs.silverstripe.org/en/4/developer_guides/files/file_storage
