### ISSUE TITLE
v1.5.0 uses PHP7 syntax, but should be compatible to PHP 5.6+

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-assets#417]
I noticed this with my travis setup, where I run tests on PHP 5.6.
The dependencies of `v1.5.0` are all PHP 5.6 compatible, and `composer.json` does not specify any PHP requirement. Thus `1.5.0` will install in a 5.6 environment, but it contains code that uses PHP 7 syntax. This is the line that errors:

https://github.com/silverstripe/silverstripe-assets/blob/1.5.0/src/InterventionBackend.php#L251

Fixing this either in code or composer.json would be great. Thanks.

**Comment by dnsl48** [comment]
Hi! The assets module of version `1.5.x` comes with `CMS Recipe 4.5`. One of the changes in that release was removal of support for `5.6` and `7.0`. You could read more about it in the [changelog](https://docs.silverstripe.org/en/4/changelogs/4.5.0/#php71). That has been done long after PHP 5.6 EOL and I reckon that was a reasonable decision.
If you need it to work with PHP 5.6, you might have to consider using assets 1.4 (CMS Recipe 4.4). Please, beware this is unsupported version of Silverstripe CMS and we are no longer fixing any bugs in those outdated branches (even security or critical ones).

 - More information about supported CMS versions on the [Roadmap](https://www.silverstripe.org/software/roadmap/)
 - Silverstripe CMS release [changelogs](https://docs.silverstripe.org/en/4/changelogs/)

---

> composer.json does not specify any PHP requirement

The modules are not defining their own PHP requirements relying on the `silverstripe/framework` module

> This is the line that errors

I believe there is much more than that in other modules included into Silverstripe CMS Recipe (defined by `silverstripe/installer` module)

Sorry I could not be of more help.

**Comment by Cheddam** [comment]
A quick heads up:

We did hit an issue in the initial 4.5.0 / 1.5.0 release, where some of the core modules were not specifying `framework ^4.5` as a minimum requirement. We rely on the PHP requirement set in framework to propagate out to the rest of the core modules, so unfortunately 1.5.0 will always be installable against PHP 5, even though it contains small sections of PHP 7 code.

We've since fixed these requirements, and are making sure to update them with every minor release, so next time we bump the PHP requirement this shouldn't be an issue.

**Comment by bummzack** [comment]
@Cheddam Thanks for your explanations.
My problem is, that my module is requiring this:

    "silverstripe/framework": "^4.1",
    "silverstripe/assets": "^1.1",

So the module works with older SilverStripe installs that are compatible with PHP 5.6 and newer ones that only support PHP 7+

When running PHP 5.6, it will install `silverstripe/assets` in Version `1.5`… which is just not correct, because it is not compatible with PHP 5.6. 

It should not be possible to install 1.5 with PHP 5.6 is what I'm saying. Adding a `"php" : "^7.0",` to the composer requirements would do the trick… I do **not** want to force my installation to use `silverstripe/assets` `1.4`, this is a module that should work with older and newer versions of SS4…

**Comment by kinglozzer** [comment]
> Adding a "php" : "^7.0", to the composer requirements would do the trick

Unfortunately that won’t fix it, because composer will just keep installing `1.5.0` as that tag already exists without the PHP 7 requirement in composer.json (unless we start deleting and re-creating tags, but that’s an entirely different can of worms we really don’t want to open). I’m afraid we’ve backed ourselves into a bit of a corner with this one :(

Could you change your requirements to “work around” this by avoiding 1.5.0? (untested)

```
"silverstripe/framework": "^4.1",
"silverstripe/assets": "^1.1, !=1.5.0"
```

**Comment by bummzack** [comment]
@kinglozzer Ok, I understand :) Sneaky trick with the requirements. I'll try this… or just force an installation of `silverstripe/assets 1.4.8` whenever travis runs tests on PHP 5.6
