### ISSUE TITLE
Valid HTML height/width values cause Exception in [image] shortcode

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-assets#434]
After running the `TagsToShortcode` task, a valid HTML image size of 50% was copied into the tag attribute. 
```html
<img class="image" src="some-image.png" alt="..." width="50%" height="auto" data-id="87299" data-shortcode="image" />
```

This results in an exception in the `ImageShortcodeProvider`: `InvalidArgumentException: Width must be a numeric value`.

While this is probably an edge case, I do think (editor supplied) shortcode values should be sanitized and/or fallback to sane defaults by the handler so they're unable to cause an exception?

# Pull request
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/436

**Comment by maxime-rainville** [comment]
Just clarifying what is going on here:
- Your initial HTML string had an image with a width of `50%`. 
- You ran the TagToShort task. 
- The `img` tag got converted to a shortcode ... but when the shortcode is being rendered out, an error is being thrown because the `ImageShortcodeProvider` doesn't know what to do with a `50%/auto` dimension.

Did I understand you correctly?

**Comment by micschk** [comment]
Yes that's exactly what was going on.
