### ISSUE TITLE
RFC: Option to transcode images (similar to image manipulations).

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-assets#441]
I've run into a use case where I want to serve up images using a format other than that which an image may have been uploaded as. I.e. transcoding JPG / PNG etc... to WEBP.

How would we feel about an additional transcoding feature that would allow images to be transcoded, similarly to how the manipulation API works?

E.g.

```
$Image.Format('webp').MaxWidth(260)
```

**Comment by kinglozzer** [comment]
Yes! I’ve been working around this for webp specifically with mod_pagespeed, but it makes way more sense to do it in core.

Looks like @maxime-rainville’s work here is very much related to this: https://github.com/silverstripe/silverstripe-assets/pull/411

**Comment by maxime-rainville** [comment]
To summarise the PoC, basically our current asset abstractions forces all your variants to have the same extension as the master file. That limit is somewhat artificial. What the PoC does is remove the limit and give developers the option to create variants with different extension. That would allow you to de things like generate thumbnails for none-images or allow you to convert files to alternative formats (e.g.: Convert a DOC to a PDF or XLS to a CSV).

My thinking at the time was give developers the API to create variants with different extensions and maybe a few examples of how to transcode files from one format to the other, but don't actually ship any built-in converters. Basically, we would give you the API to convert files, but you would have to handle the actual conversion yourself.

From the discussion we've had internally, the general feeling was that it was an interesting idea, but that there wasn't any recent or upcoming projects were we thought that this was obviously needed. The fact that more people are coming across scenarios where this could be helpful.

I'm still be keen to see it happen and think it could be interesting to see what the community does with this new API.

**Comment by micschk** [comment]
@tractorcow I've been using your https://github.com/tractorcow/silverstripe-image-formatter successfully.  
Dropping it here as another reference...

**Comment by maxime-rainville** [comment]
@silverstripe/core-team 

FYI We're looking at a partnership for getting WebP (and maybe AVIF) support in the CMS. This RFC and the matching PoC are needed to get this working.

I'd be curious to get a bit more feedback on these points.
- How much value do we put on the ability to convert images between formats and serve multiple formats via the `srcset` attribute?
- Are there alternative approaches we could take to converting images to different format aside from the "Variant with different extension" PoC?
- What API should we provide developers for them to create new converters images between formats?
  - `DataExtension` on `Image`/`File`
  - Some conversion service where you can register "Converters".
  - Something else?
 - The FileID/ParsedFileID classes are technically not part of our API. If we go ahead with this, do we need to make them an official part of our API?
- What should the API for the end-developer that convert file between format look like?
  - `$Image.Format('webp')`
  - `$Image.WebP()`
  - ???
- Are there any edge cases to consider?
  - What happens if the image is already in the correct format? (`$MyWebpImage.WebP()`)
  - What happens if the image reconverted to its original format in the correct format? (`$MyWebpImage.JPEG().WebP()`)
  - What happens if there's transformation on the image? (`$Image.SetWith(100).WebP().SetHeight(200)`)

**Comment by maxime-rainville** [comment]
I had some discussion with the core committers on Slack about this. Unless someone comes up with an objection, I'll mark this RFC accepted.

**Comment by lozcalver** [comment]
@maxime-rainville Do you think including a minimal version of #411 in SS5 would be viable? Appreciate there may still be additional UX/DX work needed for the transcoding of e.g. PDFs to JPEG previews, but it seems to me that those updates could always come later if there’s appetite for them

Other points raised above:

>How much value do we put on the ability to convert images between formats and serve multiple formats via the srcset attribute?

I don’t think this is something we should address in core - we’d need to use `<picture>` instead of a standard `<img />` for this, I don’t think that (or the decision on which formats to output) is a decision we can make in core. As long as we offer the API, people can implement it themselves in templates (or via modules).

>Are there alternative approaches we could take to converting images to different format aside from the "Variant with different extension" PoC?

The only alternative I can think of is convert-on-upload, but we have no way of knowing ahead of time which conversions someone will want take place (if any) so I don’t think it makes sense.

>What API should we provide developers for them to create new converters images between formats?

I think via extensions is fine.

>The FileID/ParsedFileID classes are technically not part of our API. If we go ahead with this, do we need to make them an official part of our API?

They don’t appear to be marked as internal/experimental, so are they not already part of our API?

>What should the API for the end-developer that convert file between format look like?

If we just include the `manipulateExtension()` API from #411, this would then be up to developers/module developers.

>What happens if the image is already in the correct format? (`$MyWebpImage.WebP()`)
>What happens if the image reconverted to its original format in the correct format? (`$MyWebpImage.JPEG().WebP()`)

These would both be decided by implementing code and would likely depend on the image backend in use. For `InterventionBackend`, as far as I can tell these would behave as expected as it just looks at the file extension at encode-time.

>What happens if there's transformation on the image? (`$Image.SetWith(100).WebP().SetHeight(200)`)

I would expect this to output a webp image with the two transformations applied. Again I think it’d depend on the image backend that’s in use correctly applying them in sequence (and not losing track of the file extension), but I’m not aware of any non-intervention backends existing!

**Comment by maxime-rainville** [comment]
We're looking at tagging CMS5 beta in the next couple days. So probably not enough time. On the plus, I thought getting this in CMS 4 without breaking changes was totally achievable. So I don't see why it wouldn't be in CMS 5.

**Comment by GuySartorelli** [comment]
This RFC has been effectively accepted.
Work will be done in https://github.com/silverstripe/silverstripe-assets/issues/488 and https://github.com/silverstripe/silverstripe-assets/issues/489
