### ISSUE TITLE
Resampled images are kept even if filesize is larger than original

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-assets#69]
# Acceptance Criteria

 * `ImageManipulation::$force_resample` changes its default from `true` to `false`
 * PHPDoc and dev docs are updated to reflect this change
 * If an image transformation is requested without requiring one (same size as the original image), the transformation is still applied to enforce the consistent application of image compression

# Notes

`ImageManipulation::$force_resample` defaults to `true`, which triggers `Resampled()` on upload (e.g. through `updateURL()`). The docs describe the feature as follows:

```
Since the 'master' images in your asset store may have a large file size, by
default SilverStripe will always apply compression to your images to save
bandwidth - even if no other manipulation (such as a crop or resize) is taking
place. If you expect the images in your asset store to already have
compression applied and want to serve up the original when no resampling is
necessary, you can add this to your mysite/config/config.yml file:
```

But: On some standard digital camera images I've uploaded, the images get *larger*. This clutters up the store with unnecessary data, right?

![image](https://user-images.githubusercontent.com/111025/30259032-6ac314f8-9712-11e7-8c35-e4860ed7f62d.png)

I'm not sure I understand this - why would anyone want their uploads to be resampled for the original downloads? I can understand setting compression ratios when image manipulation is required (resizing, cropping), but applying it to the original seems a like a bad default. It also does strange stuff like remove the embedded image profile from my digital camera uploads. And it will increase processing time overall on every upload. @dhensby @tractorcow What's the point of this feature? :D

# PR

 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/100
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7618

**Comment by tractorcow** [comment]
Well, we'd need to keep this larger image, otherwise how would we know for the future that such an image is larger? I can see the logic around not doing it, but I can't see any way of predicting the size of the resulting image that doesn't actually result in generating it.

**Comment by chillu** [comment]
Yeah, my point is that we shouldn't resample originals in the first place.

**Comment by sminnee** [comment]
When was the feature introduced? Also is this ticket essentially "change the default value of force_resample"?

**Comment by dhensby** [comment]
@jonom was the author of this change originally. Perhaps the issue is also that with the intervention backend the resample quality was increased?

I'd be happy to turn this off, to be honest.

**Comment by jonom** [comment]
Hey guys, I'll try to shed some light.

**Background**

The 'force resample' feature was actually [added by @stevie-mayhew](https://github.com/silverstripe/silverstripe-framework/pull/3265), and it was a sensible idea I think. Before the change, if you tried to crop a 500x250px image to 500x250px, you would get the original file, since no cropping was really necessary.

The problem with that is that if your original was a high quality image (e.g. 100% quality / 0% compressed jpeg) it might be a large file size that is not suitable for web purposes. In that case, applying the project's default compression (e.g. quality: 90) through a 'force resample' is a good idea to reduce file size. It also gives you the benefit of consistency in image output (e.g. any stripping of profiles or metadata that happens to cropped images will happen to all images).

> But: On some standard digital camera images I've uploaded, the images get larger.

This is the problem I tried to address with https://github.com/silverstripe/silverstripe-framework/commit/40cc567c368cc8bc633c2486ca2c420bb1256924. As long as you're always uploading high quality (minimal compression) images, forcing resampling should be a good idea. But if an image is uploaded to the CMS that has already been significantly compressed, forcing it to resample again may result in an image of poorer quality and larger file size. The change I made was to apply a force resample to the original image, but only return it if it is actually smaller than the original file. If the resampled file is larger you get the original instead.

**Going forward**

> This clutters up the store with unnecessary data, right?

Hopefully I've explained why these features are a good idea, but I agree with @chillu that when the resampled version is larger than the original, leaving it to clutter up the file store does seem a bit silly. Maybe it would be better to have a boolean flag on the Image object so if we try and fail to produce a smaller image through a force resample, we can record the attempt and know not to try again? Then the resampled version could be deleted.

**Docs**

I tried to clarify this functionality with https://github.com/silverstripe/silverstripe-framework/pull/7080/files but maybe I didn't go far enough? :) perhaps someone else wants to have a crack. Might be worth noting too that if you choose to leave `force_resample` turned on, you should instruct CMS users to always upload high quality images with minimal compression and let SilverStripe handle output compression. This is my preferred practice and means your asset store becomes a source of high quality originals that can adapt to various output requirements as your site changes.

Related: https://github.com/silverstripe/silverstripe-assets/issues/21#issuecomment-311714475

**Comment by jonom** [comment]
> And it will increase processing time overall on every upload

I didn't address this but I wasn't aware that the resampled version was being generated on upload. The intention was that resampling would happen on demand once a user is trying to access the image. Not sure what context this is happening but maybe `getSourceURL()` needs to be used in place of `getURL()` somewhere to bypass resampling? That is a shortcut directly to the actual original file.

**Comment by chillu** [comment]
Thanks for explaining this at depth, Jono!

> I didn't address this but I wasn't aware that the resampled version was being generated on upload. 

The `FileTypeCreator` GraphQL type uses `File->getAbsoluteURL()` which in turn uses `File->getURL()`. `getURL()` is the 3.x API, and hence the "main" way to get the URL for a file, right? There's also thumbnails generated directly on upload (through `CreateFileMutationCreator`), which might force the resample before those files are queried through `ReadFileQueryCreator` and the `FileTypeCreator` type later on.

> It also gives you the benefit of consistency in image output (e.g. any stripping of profiles or metadata that happens to cropped images will happen to all images).

Not sure I agree with this: As an author, I expect a resized/cropped/modified version of the image to be different. But if I add a link to a thumbnail saying "download original", I expect it to be the original I've uploaded. Stripping metadata from originals could be an opt-in feature (probably even per-upload), but at the moment it feels more like an accidental side effect. We occasionally market SilverStripe as a "lightweight digital asset management" to customers, and you wouldn't expect a DAM to muck with your source data.

> But if an image is uploaded to the CMS that has already been significantly compressed, forcing it to resample again may result in an image of poorer quality and larger file size

That's the thing, those images come straight from my digital camera, so have minimal JPEG compression. Maybe GD just doesn't have JPEG algos which are as efficient?

Overall, I think `force_resample=false` is a better default, because it speeds up processing, saves disk space on the server and is closer to the expected behaviour by the average user and dev IMHO.

**Comment by chillu** [comment]
> Before the change, if you tried to crop a 500x250px image to 500x250px, you would get the original file, since no cropping was really necessary.

You should be able to detect a manipulation through `ImageManipulation->manipulateImage()` and resize regardless of the original's dimensions, right? If a manipulation is requested rather than the original file, it should check for the presence of a manipulated file on the filesystem.

**Comment by jonom** [comment]
I don't really mind if `force_resample=false` becomes the default. That actually was the default when Stevie introduced it, and I thought most projects would benefit from it being switched on (after the patch I added). I hadn't considered an impact on performance or disk usage though so certainly making it opt-in is fine by me :) docs would just need a bit of tweaking.

> But if I add a link to a thumbnail saying "download original", I expect it to be the original I've uploaded

Totally, that's when you would use `getSourceURL()` instead of `getURL()` for the link.

> That's the thing, those images come straight from my digital camera, so have minimal JPEG compression. Maybe GD just doesn't have JPEG algos which are as efficient?

I'm really surprised by that, but yeah maybe GD jpg algos suck. Or maybe your camera is set to save a medium or low quality image? What is the [image quality](https://docs.silverstripe.org/en/4/developer_guides/files/images/#resampled-image-quality) set to in your environment?

**Comment by chillu** [comment]
> I'm really surprised by that, but yeah maybe GD jpg algos suck. Or maybe your camera is set to save a medium or low quality image? What is the image quality set to in your environment?

Actually, some images come from my iPhone 6, which doesn't even allow me to set a low quality - and they have the same problem (going from 950kb to 1.3MB). Image quality is whatever the default is on an SS4 stock install.

OK, I've added ACs to reflect the discussion - change the default to `false`, and compress on same size (only when actually performing a manipulation).

**Comment by chillu** [comment]
Removing from milestone, it's not a big deal in the bigger picture of the beta release.

**Comment by tractorcow** [comment]
Note: Setting force_resample to false by default would partially resolve https://github.com/silverstripe/silverstripe-asset-admin/issues/536
